disable webp

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -429,20 +429,20 @@ if command_exists "python3"; then
     if build "dav1d" "0.9.2"; then
       download "https://code.videolan.org/videolan/dav1d/-/archive/0.9.2/dav1d-0.9.2.tar.gz"
       make_dir build
-      
+
       CFLAGSBACKUP=$CFLAGS
       if $MACOS_M1; then
         export CFLAGS="-arch arm64"
       fi
-      
+
       execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
       execute ninja -C build
       execute ninja -C build install
-      
+
       if $MACOS_M1; then
         export CFLAGS=$CFLAGSBACKUP
       fi
-      
+
       build_done "dav1d" "0.9.2"
     fi
     CONFIGURE_OPTIONS+=("--enable-libdav1d")
@@ -785,22 +785,22 @@ if build "libpng" "1.6.37"; then
 fi
 
 ## does not compile on monterey -> _PrintGifError
-if [[ "$OSTYPE" != "darwin"* ]]; then
-  if build "libwebp" "1.2.1"; then
-    # libwebp can fail to compile on Ubuntu if these flags were left set to CFLAGS
-    CPPFLAGS=
-    download "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.1.tar.gz" "libwebp-1.2.1.tar.gz"
-    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static --disable-dependency-tracking --disable-gl --with-zlib-include="${WORKSPACE}"/include/ --with-zlib-lib="${WORKSPACE}"/lib
-    make_dir build
-    cd build || exit
-    execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include -DENABLE_SHARED=OFF -DENABLE_STATIC=ON ../
-    execute make -j $MJOBS
-    execute make install
-
-    build_done "libwebp" "1.2.1"
-  fi
-  CONFIGURE_OPTIONS+=("--enable-libwebp")
-fi
+# if [[ "$OSTYPE" != "darwin"* ]]; then
+#   if build "libwebp" "1.2.1"; then
+#     # libwebp can fail to compile on Ubuntu if these flags were left set to CFLAGS
+#     CPPFLAGS=
+#     download "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.1.tar.gz" "libwebp-1.2.1.tar.gz"
+#     execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static --disable-dependency-tracking --disable-gl --with-zlib-include="${WORKSPACE}"/include/ --with-zlib-lib="${WORKSPACE}"/lib
+#     make_dir build
+#     cd build || exit
+#     execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include -DENABLE_SHARED=OFF -DENABLE_STATIC=ON ../
+#     execute make -j $MJOBS
+#     execute make install
+#
+#     build_done "libwebp" "1.2.1"
+#   fi
+#   CONFIGURE_OPTIONS+=("--enable-libwebp")
+# fi
 ##
 ## other library
 ##
